2024-12-11 00:36:47,271 - root - INFO - Starting application...
2024-12-11 00:36:47,271 - database - INFO - Testing database connection...
2024-12-11 00:36:47,294 - database - INFO - Database connection successful!
2024-12-11 00:36:47,304 - root - INFO - Database tables verified
2024-12-11 00:37:17,484 - database - ERROR - Database session error: 
2024-12-11 00:37:17,485 - database - ERROR - Traceback (most recent call last):
  File "/home/guga-chavle/PycharmProjects/app/database.py", line 48, in get_db
    yield db
fastapi.exceptions.HTTPException

2024-12-11 00:38:00,286 - database - ERROR - Database session error: 
2024-12-11 00:38:00,286 - database - ERROR - Traceback (most recent call last):
  File "/home/guga-chavle/PycharmProjects/app/database.py", line 48, in get_db
    yield db
fastapi.exceptions.HTTPException

2024-12-11 00:39:45,454 - root - INFO - Shutting down application...
